name: Unit Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit Tests
    strategy:
      matrix:
        go-version:
        - 1.18.x
        platform:
        - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test
      run: go test ./... -v -race -coverprofile cover.out
